config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  resources :items, except: [:show]
  resources :warehouses, only: [:index, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :description
  belongs_to :warehouse, optional: true

  def self.alphabetically
    order(:name)
  end
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  has_many :items

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def error_message(errors)
    errors.full_messages.join(', ')
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :get_item, only: [:update, :destroy]

  def index
    if params[:sort]
      @items = Item.order(:warehouse_id)
    else
      @items = Item.alphabetically
    end
  end

  def create
    check_warehouse
    item = Item.create(item_params)
    if item.save
      flash[:notice] = "#{item.name} Has Been Created!"
    else
      flash[:alert] = "Error: #{error_message(item.errors)}"
    end
    redirect_to items_path
  end

  def edit
    redirect_to :controller => "items", :action => "index", :edit => true, :id => params[:id]
  end

  def update
    @item.update(item_params)
    if @item.save
      flash[:notice] = "#{@item.name} Has Been Updated!"
    else
      flash[:alert] = "Error: #{error_message(@item.errors)}"
    end
    redirect_to items_path
  end

  def destroy
    @item.destroy!
    flash[:notice] = "#{@item.name} Has Been Deleted!"
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description,:warehouse_id)
  end

  def get_item
    @item = Item.find_by(id: params[:id])
  end

  def check_warehouse
    params[:warehouse_id] == "" ? params[:warehouse_id] = nil : params[:warehouse_id]
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  def index
    @warehouses = Warehouse.all
  end

  def create
    warehouse = Warehouse.create(warehouse_params)
    if warehouse.save
      flash[:notice] = "#{warehouse.name} Has Been Created!"
    else
      flash[:alert] = "Error: #{error_message(warehouse.errors)}"
    end
    redirect_to warehouses_path
  end

  def show
    @warehouse = Warehouse.find_by(id: params[:id])
  end

  private

  def warehouse_params
    params.require(:warehouse).permit(:name, :location)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index;end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_midtable_edit.html.erb
<div class="edit_form">
  <%= form_with model: item, local: true do |f| %>
    <th scope="row"><%= f.text_field :name, value: item.name %>
    <th scope="row"><%= f.text_field :description, value: item.description %>
    <th scope="row"><%= f.collection_select :warehouse_id, Warehouse.order(:name),:id,:name, include_blank: true , value: item.warehouse_id %><br><br>
    <th scope="row"><%= f.submit "Update Item", method: :update  %>
  <% end %>
</div>

app/views/items/index.html.erb
<center>
  <h1>ALL ITEMS</h1>
  <%= link_to "Sort A-Z", items_path, method: :get %><br>
  <%= link_to "Sort by Warehouse", "/items?sort=warehouse", method: :get %><br><br>
  <div class="table_style">
    <table class="table">
      <thead class= 'thead-dark'>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Warehouse</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <% if params[:edit] && (item.id == params[:id].to_i) %>
            <%= render partial: 'midtable_edit', locals: {item: item }%>
          <% else %>
            <th scope="row"><%= item.name %></th>
            <th scope="row"><%= item.description %></th>
            <% if item.warehouse.nil? %>
              <%= form_with model: item, action: 'patch', local: true do |f| %>
                  <th scope="row"><%= f.collection_select :warehouse_id, Warehouse.order(:id), :id,:name,include_blank: false %>
                                  <%= button_to "Assign" %></th>
              <% end %>
            <% else %>
              <th scope="row"><%= item.warehouse.name %></th>
            <% end %>
              <th scope="row"><%= button_to "Edit", edit_item_path(item), method: :get %></th>
              <th scope="row"><%= button_to "Delete", item_path(item), method: :delete %></th>
          <% end %>
        <% end %>
        </tr>
      </tbody>
    </table>
  </div>

  <h4> CREATE NEW ITEM </h4>
    <%= form_with model: Item.new , local: true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.label :warehouse %>
    <%= f.collection_select :warehouse_id, Warehouse.order(:name),:id,:name, include_blank: true %>
    <%= f.submit "Create Item" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<style>
  .table_style {
position: relative;
height: 500px;
width: 1000px;
overflow: auto;
display: block;
}
</style>
  <head>
    <title>ShopifyInternApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= link_to "Home", root_path, method: :get %>
    <%= link_to "Items", items_path, method: :get %>
    <%= link_to "Warehouses", warehouses_path, method: :get %>
  </head>
    <% flash.each do |type, notice| %>
      <center>
        <h3 style="color:red;"><%= notice %></h3>
      </center>
    <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/warehouses/index.html.erb
<center>
  <h1>ALL WAREHOUSES</h1>
  <div class="table_style">
    <table class="table">
      <thead class= 'table-dark'>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Location</th>
        </tr>
      </thead>
      <tbody>
        <% @warehouses.each do |warehouse| %>
        <tr>
            <th scope="row"><%= link_to "#{warehouse.name}", warehouse_path(warehouse), method: :get %></th>
            <th scope="row"><%= warehouse.location %></th>
        <%end%>
      </tbody>
    </table>
  </div>
  <h4> CREATE NEW WAREHOUSE </h4>
    <%= form_with model: Warehouse.new, local: true do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name%>
        <%= f.label :location %>
        <%= f.text_field :location %>
        <%= f.submit "Create Warehouse" %>
    <% end %>
</center>

app/views/warehouses/show.html.erb
<center>
  <h1><%= @warehouse.name %></h1>
  <h3><%= @warehouse.location %></h3><br>
  <h3><%= "ALL ITEMS" %></h3>
  <% if @warehouse.items.empty? %>
    <h3> THIS WAREHOUSE IS EMPTY </h3>
  <% else %>
    <div class="table_style">
      <table class="table">
        <thead class= 'table-dark'>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
          </tr>
        </thead>
        <tbody>

            <% @warehouse.items.each do |item| %>

            <tr>
              <th scope="row"><%= item.name %></th>
              <th scope="row"><%= item.description %></th>
            <%end%>
        </tbody>
      </table>
    </div>
  <%end%>

app/views/welcome/index.html.erb
<center>
  <h1>Inventory</h1>
  <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-card-checklist" viewBox="0 0 16 16">
    <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
    <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0zM7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0z"/>
  </svg>

  <%= button_to "Items", items_path, method: 'get' %><br>
  <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
    <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"></path>
  </svg>
  <%= button_to "Warehouses", warehouses_path, method: :get %>
</center>